#!/usr/bin/env node

var exec = require('child_process').exec;
var path = require('path');

var child = exec(path.join(__dirname, '..', 'node_modules', '.bin', 'blacklisted-gulp'),
		function(error, stdout, stderr) {
	if (error === null) {
		console.log('/* -- Blacklisted gulp plugins -- */');
		console.log(stdout);
	} else {
		console.err(stderr);
		throw error;
	}
});